/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorUsuario;
import Controladores.controladorDevoluciones;
import Controladores.controladorPrestamo;
import Funciones.Validaciones;
import java.awt.Color;

/**
 *
 * @author ederd
 */
public class Devoluciones extends javax.swing.JFrame {
Validaciones validaciones=new Validaciones();  
    /**
     * Creates new form Devoluciones
     */
    public Devoluciones() {
        initComponents();
        lblValidacion.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        ImagenLogin = new javax.swing.JLabel();
        lblValidacion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtFechaP = new javax.swing.JTextField();
        txtFechaD = new javax.swing.JTextField();
        btnDevolver = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaDevoluciones = new javax.swing.JTable();
        txtBuscadorPrestamos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JInicio = new javax.swing.JMenu();
        JUsuarios = new javax.swing.JMenu();
        JLibros = new javax.swing.JMenu();
        JPrestamo = new javax.swing.JMenu();
        JDevoluciones = new javax.swing.JMenu();
        JMultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));

        panelDatos.setBackground(new java.awt.Color(187, 222, 251));
        panelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelDatos.setForeground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/leer.png"))); // NOI18N
        panelDatos.add(ImagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        lblValidacion.setBackground(new java.awt.Color(255, 51, 51));
        lblValidacion.setForeground(new java.awt.Color(0, 0, 0));
        lblValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidacion.setText("Correo no valido");
        lblValidacion.setOpaque(true);
        panelDatos.add(lblValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, -1));

        txtNombre.setEditable(false);
        txtNombre.setText("Nombre");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        panelDatos.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 174, -1));

        txtApellidoM.setEditable(false);
        txtApellidoM.setText("Apellido Materno");
        txtApellidoM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMMouseClicked(evt);
            }
        });
        txtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyReleased(evt);
            }
        });
        panelDatos.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 174, -1));

        txtId.setEditable(false);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setText("Id");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        panelDatos.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 70, -1));

        txtApellidoP.setEditable(false);
        txtApellidoP.setText("Apellido Paterno");
        txtApellidoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoPMouseClicked(evt);
            }
        });
        txtApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyReleased(evt);
            }
        });
        panelDatos.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 174, -1));

        txtTitulo.setEditable(false);
        txtTitulo.setText("Titulo");
        txtTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTituloMouseClicked(evt);
            }
        });
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTituloKeyReleased(evt);
            }
        });
        panelDatos.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 174, -1));

        txtFechaP.setEditable(false);
        txtFechaP.setText("Fecha Prestamo");
        txtFechaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaPMouseClicked(evt);
            }
        });
        txtFechaP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaPKeyReleased(evt);
            }
        });
        panelDatos.add(txtFechaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 174, -1));

        txtFechaD.setEditable(false);
        txtFechaD.setText("Fecha Devolucion");
        txtFechaD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtFechaDMouseClicked(evt);
            }
        });
        txtFechaD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaDKeyReleased(evt);
            }
        });
        panelDatos.add(txtFechaD, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 174, -1));

        btnDevolver.setBackground(new java.awt.Color(255, 64, 129));
        btnDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/devolver.png"))); // NOI18N
        btnDevolver.setText("Devolver");
        btnDevolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDevolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDevolverMouseExited(evt);
            }
        });
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });
        panelDatos.add(btnDevolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 320, 230, -1));

        tablaDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Id Usuairo", "Nombre", "Apellido Paterno", "Apellido Materno", "Id libro", "Título", "Fecha Prestamo", "Fecha Devolución estimada"
            }
        ));
        tablaDevoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDevolucionesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaDevoluciones);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jScrollPane2.setViewportView(jPanel2);

        txtBuscadorPrestamos.setText("Buscar");
        txtBuscadorPrestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorPrestamosMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/www.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscadorPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscadorPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );

        JInicio.setText("Incio");
        jMenuBar1.add(JInicio);

        JUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/people_114360.png"))); // NOI18N
        JUsuarios.setText("Usuarios");
        JUsuarios.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JUsuariosMenuSelected(evt);
            }
        });
        jMenuBar1.add(JUsuarios);

        JLibros.setBackground(new java.awt.Color(51, 51, 255));
        JLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro-de-registro.png"))); // NOI18N
        JLibros.setText("Libros");
        jMenuBar1.add(JLibros);

        JPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pedir-prestado.png"))); // NOI18N
        JPrestamo.setText("Prestamos");
        JPrestamo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JPrestamoMenuSelected(evt);
            }
        });
        jMenuBar1.add(JPrestamo);

        JDevoluciones.setBackground(new java.awt.Color(51, 51, 255));
        JDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/devoluciones (1).png"))); // NOI18N
        JDevoluciones.setText("Devoluciones");
        JDevoluciones.setOpaque(true);
        jMenuBar1.add(JDevoluciones);

        JMultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/multa.png"))); // NOI18N
        JMultas.setText("Multas");
        jMenuBar1.add(JMultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JUsuariosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JUsuariosMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Usuarios2 vista=new Usuarios2();
        ControladorUsuario controlador =new ControladorUsuario(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JUsuariosMenuSelected

    private void JPrestamoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JPrestamoMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Prestamos vista=new Prestamos();
        controladorPrestamo controlador=new controladorPrestamo(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JPrestamoMenuSelected

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtNombre, lblValidacion);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMMouseClicked
        // TODO add your handling code here:
        txtApellidoM.setText("");
    }//GEN-LAST:event_txtApellidoMMouseClicked

    private void txtApellidoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtApellidoM, lblValidacion);
    }//GEN-LAST:event_txtApellidoMKeyReleased

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnDevolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseEntered
        // TODO add your handling code here:
        btnDevolver.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnDevolverMouseEntered

    private void btnDevolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDevolverMouseExited
        // TODO add your handling code here:
        btnDevolver.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnDevolverMouseExited

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void tablaDevolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDevolucionesMouseClicked

            // TODO add your handling code here:
            txtId.setText(""+tablaDevoluciones.getValueAt(tablaDevoluciones.getSelectedRow(), 0));
            txtNombre.setText(""+tablaDevoluciones.getValueAt(tablaDevoluciones.getSelectedRow(), 2));
            txtApellidoP.setText(""+tablaDevoluciones.getValueAt(tablaDevoluciones.getSelectedRow(), 3));
            txtApellidoM.setText(""+tablaDevoluciones.getValueAt(tablaDevoluciones.getSelectedRow(), 4));
            txtTitulo.setText(""+tablaDevoluciones.getValueAt(tablaDevoluciones.getSelectedRow(), 6));
            txtFechaP.setText(""+tablaDevoluciones.getValueAt(tablaDevoluciones.getSelectedRow(), 7));
            txtFechaD.setText(""+tablaDevoluciones.getValueAt(tablaDevoluciones.getSelectedRow(), 8));
    }//GEN-LAST:event_tablaDevolucionesMouseClicked

    private void txtBuscadorPrestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorPrestamosMouseClicked
        // TODO add your handling code here:
        txtBuscadorPrestamos.setText("");
    }//GEN-LAST:event_txtBuscadorPrestamosMouseClicked

    private void txtApellidoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPMouseClicked

    private void txtApellidoPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPKeyReleased

    private void txtTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTituloMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloMouseClicked

    private void txtTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTituloKeyReleased

    private void txtFechaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPMouseClicked

    private void txtFechaPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPKeyReleased

    private void txtFechaDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFechaDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDMouseClicked

    private void txtFechaDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaDKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Devoluciones vista=new Devoluciones();
        controladorDevoluciones con=new controladorDevoluciones(vista);
         vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenLogin;
    private javax.swing.JMenu JDevoluciones;
    private javax.swing.JMenu JInicio;
    private javax.swing.JMenu JLibros;
    private javax.swing.JMenu JMultas;
    private javax.swing.JMenu JPrestamo;
    private javax.swing.JMenu JUsuarios;
    public javax.swing.JButton btnDevolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblValidacion;
    public javax.swing.JPanel panelDatos;
    public javax.swing.JTable tablaDevoluciones;
    public javax.swing.JTextField txtApellidoM;
    public javax.swing.JTextField txtApellidoP;
    public javax.swing.JTextField txtBuscadorPrestamos;
    public javax.swing.JTextField txtFechaD;
    public javax.swing.JTextField txtFechaP;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
