/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorUsuario;
import Controladores.controladorLibro;
import Controladores.controladorPrestamo;
import Funciones.Validaciones;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author ederd
 */
public class Libros extends javax.swing.JFrame {
    SimpleDateFormat formatoFecha= new SimpleDateFormat("yyyy-MM-dd");
        Validaciones validaciones=new Validaciones();  

    /**
     * Creates new form Libros
     */
    public Libros() {
        initComponents();
        lblValidacion.setVisible(false);
        tablaLibros.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        ImagenLogin = new javax.swing.JLabel();
        lblValidacion = new javax.swing.JLabel();
        txtNúmeroCopias = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        fechaPublicacion = new com.toedter.calendar.JDateChooser();
        txtIsbn = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        txtBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JInicio = new javax.swing.JMenu();
        JUsuarios = new javax.swing.JMenu();
        JLibros = new javax.swing.JMenu();
        JPrestamo = new javax.swing.JMenu();
        JDevoluciones = new javax.swing.JMenu();
        JMultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));

        panelDatos.setBackground(new java.awt.Color(187, 222, 251));
        panelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelDatos.setForeground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pila-de-libros.png"))); // NOI18N
        panelDatos.add(ImagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        lblValidacion.setBackground(new java.awt.Color(255, 51, 51));
        lblValidacion.setForeground(new java.awt.Color(0, 0, 0));
        lblValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidacion.setText("Correo no valido");
        lblValidacion.setOpaque(true);
        panelDatos.add(lblValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 290, -1));

        txtNúmeroCopias.setText("Número Copias");
        txtNúmeroCopias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNúmeroCopiasMouseClicked(evt);
            }
        });
        txtNúmeroCopias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNúmeroCopiasActionPerformed(evt);
            }
        });
        txtNúmeroCopias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNúmeroCopiasKeyReleased(evt);
            }
        });
        panelDatos.add(txtNúmeroCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 174, -1));

        txtTitulo.setText("Titulo");
        txtTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTituloMouseClicked(evt);
            }
        });
        txtTitulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTituloKeyReleased(evt);
            }
        });
        panelDatos.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 174, -1));

        txtAutor.setText("Autor");
        txtAutor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAutorMouseClicked(evt);
            }
        });
        txtAutor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAutorKeyReleased(evt);
            }
        });
        panelDatos.add(txtAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 174, -1));
        panelDatos.add(fechaPublicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 174, -1));

        txtIsbn.setText("ISBN");
        txtIsbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIsbnMouseClicked(evt);
            }
        });
        txtIsbn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIsbnKeyReleased(evt);
            }
        });
        panelDatos.add(txtIsbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 174, -1));

        txtEditorial.setText("Editorial");
        txtEditorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEditorialMouseClicked(evt);
            }
        });
        txtEditorial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEditorialKeyReleased(evt);
            }
        });
        panelDatos.add(txtEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 174, -1));

        txtId.setEditable(false);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setText("Id");
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        panelDatos.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 70, -1));

        btnInsertar.setBackground(new java.awt.Color(255, 64, 129));
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-contacto.png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertarMouseExited(evt);
            }
        });
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 64, 129));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bloc-de-dibujo.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 64, 129));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titúlo", "Autór", "Fecha Publicación", "ISBN", "Editorial", "Número copias"
            }
        ));
        tablaLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLibrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaLibros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jScrollPane2.setViewportView(jPanel2);

        txtBuscador.setText("Buscar");
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/www.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        JInicio.setText("Incio");
        jMenuBar1.add(JInicio);

        JUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/people_114360.png"))); // NOI18N
        JUsuarios.setText("Usuarios");
        JUsuarios.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JUsuariosMenuSelected(evt);
            }
        });
        jMenuBar1.add(JUsuarios);

        JLibros.setBackground(new java.awt.Color(51, 51, 255));
        JLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro-de-registro.png"))); // NOI18N
        JLibros.setText("Libros");
        JLibros.setOpaque(true);
        jMenuBar1.add(JLibros);

        JPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pedir-prestado.png"))); // NOI18N
        JPrestamo.setText("Prestamos");
        JPrestamo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JPrestamoMenuSelected(evt);
            }
        });
        jMenuBar1.add(JPrestamo);

        JDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/devoluciones (1).png"))); // NOI18N
        JDevoluciones.setText("Devoluciones");
        jMenuBar1.add(JDevoluciones);

        JMultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/multa.png"))); // NOI18N
        JMultas.setText("Multas");
        jMenuBar1.add(JMultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNúmeroCopiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNúmeroCopiasMouseClicked
        // TODO add your handling code here:
        txtNúmeroCopias.setText("");
    }//GEN-LAST:event_txtNúmeroCopiasMouseClicked

    private void txtNúmeroCopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNúmeroCopiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNúmeroCopiasActionPerformed

    private void txtTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTituloMouseClicked
        // TODO add your handling code here:
        txtTitulo.setText("");
    }//GEN-LAST:event_txtTituloMouseClicked

    private void txtTituloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTituloKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtTitulo, lblValidacion);
    }//GEN-LAST:event_txtTituloKeyReleased

    private void txtAutorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAutorMouseClicked
        // TODO add your handling code here:
        txtAutor.setText("");
    }//GEN-LAST:event_txtAutorMouseClicked

    private void txtAutorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAutorKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtAutor, lblValidacion);
    }//GEN-LAST:event_txtAutorKeyReleased

    private void txtIsbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIsbnMouseClicked
        // TODO add your handling code here:
        txtIsbn.setText("");
    }//GEN-LAST:event_txtIsbnMouseClicked

    private void txtIsbnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIsbnKeyReleased
        // TODO add your handling code here:
        validaciones.validacionTelefono(txtIsbn, txtIsbn, lblValidacion);
    }//GEN-LAST:event_txtIsbnKeyReleased

    private void txtEditorialMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEditorialMouseClicked
        // TODO add your handling code here:
        txtEditorial.setText("");
    }//GEN-LAST:event_txtEditorialMouseClicked

    private void btnInsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseEntered
        // TODO add your handling code here:
        btnInsertar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnInsertarMouseEntered

    private void btnInsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseExited
        // TODO add your handling code here:
        btnInsertar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnInsertarMouseExited

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibrosMouseClicked
        try {
            // TODO add your handling code here:
            txtId.setText(""+tablaLibros.getValueAt(tablaLibros.getSelectedRow(), 0));
            txtTitulo.setText(""+tablaLibros.getValueAt(tablaLibros.getSelectedRow(), 1));
            txtAutor.setText(""+tablaLibros.getValueAt(tablaLibros.getSelectedRow(), 2));
            fechaPublicacion.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String) tablaLibros.getValueAt(tablaLibros.getSelectedRow(), 3)));
            txtIsbn.setText(""+tablaLibros.getValueAt(tablaLibros.getSelectedRow(), 4));
            txtEditorial.setText(""+tablaLibros.getValueAt(tablaLibros.getSelectedRow(), 5));
            txtNúmeroCopias.setText(""+tablaLibros.getValueAt(tablaLibros.getSelectedRow(), 6));
            

        } catch (ParseException ex) {
            Logger.getLogger(Usuarios2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tablaLibrosMouseClicked

    private void txtBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMouseClicked
        // TODO add your handling code here:
        txtBuscador.setText("");
    }//GEN-LAST:event_txtBuscadorMouseClicked

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtNúmeroCopiasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNúmeroCopiasKeyReleased
        // TODO add your handling code here:
        validaciones.validacionTelefono(txtNúmeroCopias, txtNúmeroCopias, lblValidacion);
    }//GEN-LAST:event_txtNúmeroCopiasKeyReleased

    private void txtEditorialKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEditorialKeyReleased
        // TODO add your handling code here:
         validaciones.getValidacionLetras(txtEditorial, lblValidacion);
    }//GEN-LAST:event_txtEditorialKeyReleased

    private void JUsuariosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JUsuariosMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Usuarios2 vista=new Usuarios2();
        ControladorUsuario controlador =new ControladorUsuario(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JUsuariosMenuSelected

    private void JPrestamoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JPrestamoMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Prestamos vista=new Prestamos();
        controladorPrestamo controlador=new controladorPrestamo(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JPrestamoMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Libros vista=new Libros();
        controladorLibro controlador=new controladorLibro(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenLogin;
    private javax.swing.JMenu JDevoluciones;
    private javax.swing.JMenu JInicio;
    private javax.swing.JMenu JLibros;
    private javax.swing.JMenu JMultas;
    private javax.swing.JMenu JPrestamo;
    private javax.swing.JMenu JUsuarios;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnInsertar;
    public com.toedter.calendar.JDateChooser fechaPublicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblValidacion;
    public javax.swing.JPanel panelDatos;
    public javax.swing.JTable tablaLibros;
    public javax.swing.JTextField txtAutor;
    public javax.swing.JTextField txtBuscador;
    public javax.swing.JTextField txtEditorial;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtIsbn;
    public javax.swing.JTextField txtNúmeroCopias;
    public javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
