/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.controladorLogin;
import Controladores.controladorRegistrarUsuario;
import Vistas.RegistarUsuario;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import modelo.modeloLogin;
import modelo.modeloRegistrarUsuario;

/**
 *
 * @author ederd
 */
public class Login extends javax.swing.JFrame {
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        lblValidacion.setVisible(false);
        baseDatos.connect();
         //showWindows(new RegistarUsuario());
    }
    public void showWindows(JPanel vista){
        vista.setSize(120, 120);
        vista.setLocation(0,0);
        
        panelPrincipal.removeAll();
        panelPrincipal.add(vista,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseDatos = new novisualbd.NoVisualBD();
        panelFondo = new javax.swing.JPanel();
        lblBiblotecaHorizontal = new javax.swing.JLabel();
        LogoLibreria = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        ImagenLogin = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        ImagenCorreo = new javax.swing.JLabel();
        ImagenContrasena = new javax.swing.JLabel();
        Pasword = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        lblIniciarSesion = new javax.swing.JLabel();
        VerPasword = new javax.swing.JToggleButton();
        lblValidacion = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();

        baseDatos.setBd("biblioteca2");
        baseDatos.setIp("localhost");
        baseDatos.setPassword("Pooh17");
        baseDatos.setPuerto("3306");
        baseDatos.setUser("root");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(33, 150, 243));
        panelFondo.setPreferredSize(new java.awt.Dimension(1250, 625));

        lblBiblotecaHorizontal.setFont(new java.awt.Font("Segoe UI Semilight", 3, 36)); // NOI18N
        lblBiblotecaHorizontal.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblotecaHorizontal.setText("Biblioteca Horizonte Azul");

        LogoLibreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_1.jpg"))); // NOI18N

        panelPrincipal.setBackground(new java.awt.Color(187, 222, 251));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        ImagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfil-del-usuario.png"))); // NOI18N

        txtCorreo.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        txtCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCorreo.setText("Correo");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });

        ImagenCorreo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/correo (1).png"))); // NOI18N
        ImagenCorreo.setText("jLabel3");
        ImagenCorreo.setPreferredSize(new java.awt.Dimension(64, 64));

        ImagenContrasena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/restablecer-la-contrasena.png"))); // NOI18N

        Pasword.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        Pasword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Pasword.setText("Contraseña");
        Pasword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PaswordMouseClicked(evt);
            }
        });

        btnIniciarSesion.setBackground(new java.awt.Color(255, 64, 129));
        btnIniciarSesion.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciar-sesion.png"))); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setFocusPainted(false);
        btnIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnIniciarSesion.setIconTextGap(10);
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        lblIniciarSesion.setFont(new java.awt.Font("Segoe UI Semilight", 3, 36)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIniciarSesion.setText("Iniciar Sesión");

        VerPasword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/visibilidad.png"))); // NOI18N
        VerPasword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPaswordActionPerformed(evt);
            }
        });

        lblValidacion.setBackground(new java.awt.Color(255, 51, 51));
        lblValidacion.setForeground(new java.awt.Color(0, 0, 0));
        lblValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidacion.setText("Correo no valido");
        lblValidacion.setOpaque(true);

        btnRegistrar.setBackground(new java.awt.Color(255, 64, 129));
        btnRegistrar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario.png"))); // NOI18N
        btnRegistrar.setText("Registrarse");
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegistrar.setIconTextGap(10);
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(ImagenLogin))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lblValidacion, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(ImagenCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(ImagenContrasena)
                        .addGap(6, 6, 6)
                        .addComponent(Pasword, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(VerPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(ImagenLogin)
                .addGap(6, 6, 6)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblValidacion))
                    .addComponent(lblIniciarSesion))
                .addGap(12, 12, 12)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ImagenContrasena)
                    .addComponent(Pasword, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VerPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelFondoLayout = new javax.swing.GroupLayout(panelFondo);
        panelFondo.setLayout(panelFondoLayout);
        panelFondoLayout.setHorizontalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBiblotecaHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoLibreria))
                .addGap(18, 18, 18)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelFondoLayout.setVerticalGroup(
            panelFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblBiblotecaHorizontal)
                .addGap(18, 18, 18)
                .addComponent(LogoLibreria))
            .addGroup(panelFondoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void VerPaswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPaswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VerPaswordActionPerformed

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
        txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void PaswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PaswordMouseClicked
        // TODO add your handling code here:
        Pasword.setText("");
    }//GEN-LAST:event_PaswordMouseClicked

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered
        // TODO add your handling code here:
        btnIniciarSesion.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited
        // TODO add your handling code here:
        btnIniciarSesion.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        // TODO add your handling code here:
        btnRegistrar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        // TODO add your handling code here:
         btnRegistrar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        modeloRegistrarUsuario modelo=new modeloRegistrarUsuario();
        RegistarUsuario vista =new RegistarUsuario();
        controladorRegistrarUsuario controlador=new controladorRegistrarUsuario(modelo,vista);
        controlador.iniciar();
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
         Login vista=new Login();
         modeloLogin modelo=new modeloLogin();
         controladorLogin controlador=new controladorLogin(modelo,vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenContrasena;
    private javax.swing.JLabel ImagenCorreo;
    private javax.swing.JLabel ImagenLogin;
    private javax.swing.JLabel LogoLibreria;
    public javax.swing.JPasswordField Pasword;
    public javax.swing.JToggleButton VerPasword;
    public novisualbd.NoVisualBD baseDatos;
    public javax.swing.JButton btnIniciarSesion;
    public javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblBiblotecaHorizontal;
    private javax.swing.JLabel lblIniciarSesion;
    public javax.swing.JLabel lblValidacion;
    private javax.swing.JPanel panelFondo;
    public javax.swing.JPanel panelPrincipal;
    public javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
