/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorUsuario;
import Controladores.controladorDevoluciones;
import Controladores.controladorLibro;
import Controladores.controladorPrestamo;
import java.awt.Color;
import modelo.modeloPrestamo;

/**
 *
 * @author ederd
 */
public class Prestamos extends javax.swing.JFrame {
    modeloPrestamo modelo=new modeloPrestamo();

    /**
     * Creates new form Prestamos
     */
    public Prestamos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnPrestar = new javax.swing.JButton();
        btnLibrosPrestados = new javax.swing.JButton();
        txtBuscadorLibro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        txtBuscadorUsuarios = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLibros = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        JInicio = new javax.swing.JMenu();
        JUsuarios = new javax.swing.JMenu();
        JLibros = new javax.swing.JMenu();
        JPrestamo = new javax.swing.JMenu();
        JDevoluciones = new javax.swing.JMenu();
        JMultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));

        btnPrestar.setBackground(new java.awt.Color(255, 64, 129));
        btnPrestar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro (1)_1.png"))); // NOI18N
        btnPrestar.setText("Prestar");
        btnPrestar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPrestarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPrestarMouseExited(evt);
            }
        });
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        btnLibrosPrestados.setBackground(new java.awt.Color(255, 64, 129));
        btnLibrosPrestados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro (2).png"))); // NOI18N
        btnLibrosPrestados.setText("Libros Prestados");
        btnLibrosPrestados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLibrosPrestadosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLibrosPrestadosMouseExited(evt);
            }
        });
        btnLibrosPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibrosPrestadosActionPerformed(evt);
            }
        });

        txtBuscadorLibro.setText("Buscar");
        txtBuscadorLibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorLibroMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/www.png"))); // NOI18N

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuario", "Nombre", "Apellido Paterno", "Apellido Materno", "Fecha Nacimiento", "Contraseña", "Teléfono", "Correo", "Domicilio", "Tipo Usuario"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
        );

        jScrollPane4.setViewportView(jPanel3);

        txtBuscadorUsuarios.setText("Buscar");
        txtBuscadorUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorUsuariosMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/www.png"))); // NOI18N

        tablaLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titúlo", "Autór", "Fecha Publicación", "ISBN", "Editorial", "Número copias"
            }
        ));
        tablaLibros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaLibrosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaLibros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jScrollPane2.setViewportView(jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscadorUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLibrosPrestados, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(428, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscadorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscadorLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscadorUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLibrosPrestados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrestar))
                .addContainerGap())
        );

        JInicio.setText("Incio");
        jMenuBar1.add(JInicio);

        JUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/people_114360.png"))); // NOI18N
        JUsuarios.setText("Usuarios");
        JUsuarios.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JUsuariosMenuSelected(evt);
            }
        });
        jMenuBar1.add(JUsuarios);

        JLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro-de-registro.png"))); // NOI18N
        JLibros.setText("Libros");
        JLibros.setOpaque(true);
        JLibros.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JLibrosMenuSelected(evt);
            }
        });
        jMenuBar1.add(JLibros);

        JPrestamo.setBackground(new java.awt.Color(51, 51, 255));
        JPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pedir-prestado.png"))); // NOI18N
        JPrestamo.setText("Prestamos");
        JPrestamo.setOpaque(true);
        jMenuBar1.add(JPrestamo);

        JDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/devoluciones (1).png"))); // NOI18N
        JDevoluciones.setText("Devoluciones");
        JDevoluciones.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JDevolucionesMenuSelected(evt);
            }
        });
        jMenuBar1.add(JDevoluciones);

        JMultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/multa.png"))); // NOI18N
        JMultas.setText("Multas");
        jMenuBar1.add(JMultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JUsuariosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JUsuariosMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Usuarios2 vista=new Usuarios2();
        ControladorUsuario controlador =new ControladorUsuario(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JUsuariosMenuSelected

    private void btnPrestarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestarMouseEntered
        // TODO add your handling code here:
        btnPrestar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnPrestarMouseEntered

    private void btnPrestarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPrestarMouseExited
        // TODO add your handling code here:
        btnPrestar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnPrestarMouseExited

    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnLibrosPrestadosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosPrestadosMouseEntered
        // TODO add your handling code here:
        btnLibrosPrestados.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnLibrosPrestadosMouseEntered

    private void btnLibrosPrestadosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLibrosPrestadosMouseExited
        // TODO add your handling code here:
        btnLibrosPrestados.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnLibrosPrestadosMouseExited

    private void btnLibrosPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibrosPrestadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLibrosPrestadosActionPerformed

    private void txtBuscadorLibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorLibroMouseClicked
        // TODO add your handling code here:
        txtBuscadorLibro.setText("");
    }//GEN-LAST:event_txtBuscadorLibroMouseClicked

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
      //modelo.setIdUsuario(Integer.parseInt(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 0).toString()));
      //System.out.println(modelo.getIdUsuario());
      //System.out.print(modelo.getIdLibro());
        /*
        try {
            // TODO add your handling code here:
            txtId.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 0));
            txtNombreUsuario.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 1));
            txtNombre.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 2));
            txtApellidoP.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 3));
            txtApellidoM.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 4));
            fechaNacimiento.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String) tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 5)));
            visualPassword.setPassword(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 6));
            txtTelefono.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 7));
            txtCorreo.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 8));
            txtDomicilio.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 9));
            comboxTipoUsuario.setSelectedItem(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 10));

        } catch (ParseException ex) {
            Logger.getLogger(Usuarios2.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void txtBuscadorUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorUsuariosMouseClicked
        // TODO add your handling code here:
        txtBuscadorUsuarios.setText("");
    }//GEN-LAST:event_txtBuscadorUsuariosMouseClicked

    private void JLibrosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JLibrosMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Libros vista=new Libros();
        controladorLibro controlador=new controladorLibro(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JLibrosMenuSelected

    private void tablaLibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaLibrosMouseClicked
        //modelo.setIdLibro(Integer.parseInt(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 0).toString()));
    }//GEN-LAST:event_tablaLibrosMouseClicked

    private void JDevolucionesMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JDevolucionesMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Devoluciones vista=new Devoluciones();
        controladorDevoluciones con=new controladorDevoluciones(vista);
         vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JDevolucionesMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Prestamos vista=new Prestamos();
        controladorPrestamo controlador=new controladorPrestamo(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JDevoluciones;
    private javax.swing.JMenu JInicio;
    private javax.swing.JMenu JLibros;
    private javax.swing.JMenu JMultas;
    private javax.swing.JMenu JPrestamo;
    private javax.swing.JMenu JUsuarios;
    public javax.swing.JButton btnLibrosPrestados;
    public javax.swing.JButton btnPrestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable tablaLibros;
    public javax.swing.JTable tablaUsuarios;
    public javax.swing.JTextField txtBuscadorLibro;
    public javax.swing.JTextField txtBuscadorUsuarios;
    // End of variables declaration//GEN-END:variables
}
