/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.controladorLogin;
import Funciones.Validaciones;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import modelo.modeloLogin;
import modelo.modeloRegistrarUsuario;
import Funciones.Utilerias;
import java.text.SimpleDateFormat;

/**
 *
 * @author ederd
 */
public class RegistarUsuario extends javax.swing.JFrame {
    SimpleDateFormat formatoFecha= new SimpleDateFormat("yyyy-MM-dd");
    Utilerias utilerias=new Utilerias();
    modeloRegistrarUsuario modelo=new modeloRegistrarUsuario();
    Validaciones validaciones=new Validaciones();
    /**
     * Creates new form Login
     */
    public RegistarUsuario() {
        initComponents();
        lblValidacion.setVisible(false);
         //showWindows(new RegistarUsuario());
    }
    public void showWindows(JPanel vista){
        vista.setSize(120, 120);
        vista.setLocation(0,0);
        
        panelPrincipal.removeAll();
        panelPrincipal.add(vista,BorderLayout.CENTER);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        baseDatos = new novisualbd.NoVisualBD();
        panelFondo = new javax.swing.JPanel();
        lblBiblotecaHorizontal = new javax.swing.JLabel();
        LogoLibreria = new javax.swing.JLabel();
        panelPrincipal = new javax.swing.JPanel();
        ImagenLogin = new javax.swing.JLabel();
        lblValidacion = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        visualPassword1 = new novisualbd.VisualPassword();
        txtDomicilio = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        lblBiblotecaHorizontal1 = new javax.swing.JLabel();

        baseDatos.setBd("biblioteca2");
        baseDatos.setIp("localhost");
        baseDatos.setPassword("Pooh17");
        baseDatos.setPuerto("3306");
        baseDatos.setUser("root");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelFondo.setBackground(new java.awt.Color(33, 150, 243));
        panelFondo.setPreferredSize(new java.awt.Dimension(1250, 625));
        panelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBiblotecaHorizontal.setFont(new java.awt.Font("Segoe UI Semilight", 3, 36)); // NOI18N
        lblBiblotecaHorizontal.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblotecaHorizontal.setText("Biblioteca Horizonte Azul");
        panelFondo.add(lblBiblotecaHorizontal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 421, -1));

        LogoLibreria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo_1.jpg"))); // NOI18N
        panelFondo.add(LogoLibreria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 380, 480));

        panelPrincipal.setBackground(new java.awt.Color(187, 222, 251));
        panelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/registros-de-empleo.png"))); // NOI18N
        panelPrincipal.add(ImagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 8, -1, -1));

        lblValidacion.setBackground(new java.awt.Color(255, 51, 51));
        lblValidacion.setForeground(new java.awt.Color(0, 0, 0));
        lblValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidacion.setText("Correo no valido");
        lblValidacion.setOpaque(true);
        panelPrincipal.add(lblValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 142, 290, -1));

        txtNombreUsuario.setText("Nombre Usuario");
        txtNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMouseClicked(evt);
            }
        });
        panelPrincipal.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 176, 174, -1));

        txtNombre.setText("Nombre");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        panelPrincipal.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 176, 174, -1));

        txtApellidoP.setText("Apellido Paterno");
        txtApellidoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoPMouseClicked(evt);
            }
        });
        txtApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyReleased(evt);
            }
        });
        panelPrincipal.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 216, 174, -1));

        txtApellidoM.setText("Apellido Materno");
        txtApellidoM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMMouseClicked(evt);
            }
        });
        txtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyReleased(evt);
            }
        });
        panelPrincipal.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 256, 174, -1));
        panelPrincipal.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 296, 174, -1));

        txtTelefono.setText("Teléfeno");
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseClicked(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        panelPrincipal.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 336, 174, -1));

        txtCorreo.setText("Correo@gmail.com");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        panelPrincipal.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 216, 174, -1));

        visualPassword1.setBackground(new java.awt.Color(187, 222, 251));
        visualPassword1.setForeground(new java.awt.Color(255, 255, 255));
        visualPassword1.setCaracterEspecial(true);
        visualPassword1.setMaximo(10);
        visualPassword1.setMayusculas(true);
        visualPassword1.setMinimo(8);
        visualPassword1.setNumero(true);
        visualPassword1.setVisibleEtiqueta(true);
        panelPrincipal.add(visualPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 250, -1, -1));

        txtDomicilio.setText("Domicilio");
        txtDomicilio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDomicilioMouseClicked(evt);
            }
        });
        panelPrincipal.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 376, 174, -1));

        btnRegistrar.setBackground(new java.awt.Color(255, 64, 129));
        btnRegistrar.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario.png"))); // NOI18N
        btnRegistrar.setText("Registrarse");
        btnRegistrar.setFocusPainted(false);
        btnRegistrar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnRegistrar.setIconTextGap(10);
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 442, 219, 84));

        btnIniciarSesion.setBackground(new java.awt.Color(255, 64, 129));
        btnIniciarSesion.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        btnIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iniciar-sesion.png"))); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.setFocusPainted(false);
        btnIniciarSesion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnIniciarSesion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnIniciarSesion.setIconTextGap(10);
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 442, 219, 83));

        panelFondo.add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 56, 740, 550));

        lblBiblotecaHorizontal1.setFont(new java.awt.Font("Segoe UI Semilight", 3, 36)); // NOI18N
        lblBiblotecaHorizontal1.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblotecaHorizontal1.setText("Registro Nuevo Usuario");
        panelFondo.add(lblBiblotecaHorizontal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 421, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        // TODO add your handling code here:
        btnRegistrar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        // TODO add your handling code here:
        btnRegistrar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        
        modelo.setNombre(txtNombre.getText());
        modelo.setApellidoP(txtApellidoP.getText());
        modelo.setApellidoM(txtApellidoM.getText());
        modelo.setFechaNacimiento(formatoFecha.format(fechaNacimiento.getDate()));
        modelo.setTelefono(txtTelefono.getText());
        modelo.setDomicilio(txtDomicilio.getText());
        modelo.setNombreUsuario(txtNombreUsuario.getText());
        modelo.setCorreo(txtCorreo.getText());
        modelo.setContraseña(visualPassword1.generatePassword());
        modelo.setTipoUsuario("Usuario");
        if(modelo.existeUsuario()){
            utilerias.mostrarMensaje(lblValidacion, "Ese usuario ya existe", 3000);
        }
        if(modelo.existeCorreo()){
            utilerias.mostrarMensaje(lblValidacion, "Ese correo  ya esta dado de alta", 3000);
        }
        
        if(modelo.registrarUsuario()){
            JOptionPane.showMessageDialog(null,"Usuario dado de alta");
        }else{
            JOptionPane.showMessageDialog(null,"Error al dar alta");
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered
        // TODO add your handling code here:
        btnIniciarSesion.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited
        // TODO add your handling code here:
        btnIniciarSesion.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        // TODO add your handling code here:
         this.dispose();
         Login vista=new Login();
         modeloLogin modelo=new modeloLogin();
         controladorLogin controlador=new controladorLogin(modelo,vista);
         controlador.iniciar();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtNombre, lblValidacion);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtApellidoP, lblValidacion);
    }//GEN-LAST:event_txtApellidoPKeyReleased

    private void txtApellidoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtApellidoM, lblValidacion);
    }//GEN-LAST:event_txtApellidoMKeyReleased

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        validaciones.validacionTelefono(txtTelefono, txtTelefono, lblValidacion);
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtApellidoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPMouseClicked
        // TODO add your handling code here:
        txtApellidoP.setText("");
    }//GEN-LAST:event_txtApellidoPMouseClicked

    private void txtApellidoMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMMouseClicked
        // TODO add your handling code here:
        txtApellidoM.setText("");
    }//GEN-LAST:event_txtApellidoMMouseClicked

    private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
        // TODO add your handling code here:
        txtTelefono.setText("");
    }//GEN-LAST:event_txtTelefonoMouseClicked

    private void txtDomicilioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDomicilioMouseClicked
        // TODO add your handling code here:
        txtDomicilio.setText("");
    }//GEN-LAST:event_txtDomicilioMouseClicked

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
        txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtNombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMouseClicked
        // TODO add your handling code here:
        txtNombreUsuario.setText("");
    }//GEN-LAST:event_txtNombreUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenLogin;
    private javax.swing.JLabel LogoLibreria;
    public novisualbd.NoVisualBD baseDatos;
    public javax.swing.JButton btnIniciarSesion;
    public javax.swing.JButton btnRegistrar;
    private com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JLabel lblBiblotecaHorizontal;
    private javax.swing.JLabel lblBiblotecaHorizontal1;
    public javax.swing.JLabel lblValidacion;
    private javax.swing.JPanel panelFondo;
    public javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtApellidoM;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtTelefono;
    private novisualbd.VisualPassword visualPassword1;
    // End of variables declaration//GEN-END:variables
}
