/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Controladores.ControladorUsuario;
import Controladores.controladorLibro;
import Controladores.controladorPrestamo;
import Funciones.Utilerias;
import Funciones.Validaciones;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.modeloUsuario;

/**
 *
 * @author ederd
 */
public class Usuarios2 extends javax.swing.JFrame {
    SimpleDateFormat formatoFecha= new SimpleDateFormat("yyyy-MM-dd");
    Utilerias utilerias=new Utilerias();
    modeloUsuario modelo=new modeloUsuario();
    Validaciones validaciones=new Validaciones();  

    /**
     * Creates new form Usuarios2
     */
    public Usuarios2() {
        initComponents();
        lblValidacion.setVisible(false);
        tablaUsuarios.setDefaultEditor(Object.class, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        ImagenLogin = new javax.swing.JLabel();
        lblValidacion = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoP = new javax.swing.JTextField();
        txtApellidoM = new javax.swing.JTextField();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDomicilio = new javax.swing.JTextField();
        comboxTipoUsuario = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        visualPassword = new novisualbd.VisualPassword();
        btnInsertar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        txtBuscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JInicio = new javax.swing.JMenu();
        JUsuarios = new javax.swing.JMenu();
        JLibros = new javax.swing.JMenu();
        JPrestamo = new javax.swing.JMenu();
        JDevoluciones = new javax.swing.JMenu();
        JMultas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(30, 136, 229));

        panelDatos.setBackground(new java.awt.Color(187, 222, 251));
        panelDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        panelDatos.setForeground(new java.awt.Color(255, 255, 255));
        panelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImagenLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/seguidores.png"))); // NOI18N
        panelDatos.add(ImagenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 8, -1, -1));

        lblValidacion.setBackground(new java.awt.Color(255, 51, 51));
        lblValidacion.setForeground(new java.awt.Color(0, 0, 0));
        lblValidacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidacion.setText("Correo no valido");
        lblValidacion.setOpaque(true);
        panelDatos.add(lblValidacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 142, 290, -1));

        txtNombreUsuario.setText("Nombre Usuario");
        txtNombreUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreUsuarioMouseClicked(evt);
            }
        });
        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        panelDatos.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 176, 174, -1));

        txtNombre.setText("Nombre");
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreKeyReleased(evt);
            }
        });
        panelDatos.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 176, 174, -1));

        txtApellidoP.setText("Apellido Paterno");
        txtApellidoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoPMouseClicked(evt);
            }
        });
        txtApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoPKeyReleased(evt);
            }
        });
        panelDatos.add(txtApellidoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 216, 174, -1));

        txtApellidoM.setText("Apellido Materno");
        txtApellidoM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApellidoMMouseClicked(evt);
            }
        });
        txtApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidoMKeyReleased(evt);
            }
        });
        panelDatos.add(txtApellidoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 256, 174, -1));
        panelDatos.add(fechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 296, 174, -1));

        txtTelefono.setText("Teléfeno");
        txtTelefono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTelefonoMouseClicked(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyReleased(evt);
            }
        });
        panelDatos.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 336, 174, -1));

        txtCorreo.setText("Correo@gmail.com");
        txtCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCorreoMouseClicked(evt);
            }
        });
        panelDatos.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 216, 174, -1));

        txtDomicilio.setText("Domicilio");
        txtDomicilio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDomicilioMouseClicked(evt);
            }
        });
        panelDatos.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 376, 174, -1));

        comboxTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario" }));
        panelDatos.add(comboxTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 376, 149, -1));

        txtId.setEditable(false);
        txtId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtId.setText("Id");
        panelDatos.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 70, -1));

        visualPassword.setBackground(new java.awt.Color(187, 222, 251));
        visualPassword.setCaracterEspecial(true);
        visualPassword.setMaximo(12);
        visualPassword.setMayusculas(true);
        visualPassword.setMinimo(8);
        visualPassword.setMinuscula(true);
        visualPassword.setNumero(true);
        visualPassword.setVisibleEtiqueta(true);
        panelDatos.add(visualPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(255, 64, 129));
        btnInsertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregar-usuario (1).png"))); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInsertarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInsertarMouseExited(evt);
            }
        });
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 64, 129));
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuario.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditarMouseExited(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 64, 129));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/basura.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarMouseExited(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuario", "Nombre", "Apellido Paterno", "Apellido Materno", "Fecha Nacimiento", "Contraseña", "Teléfono", "Correo", "Domicilio", "Tipo Usuario"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );

        jScrollPane2.setViewportView(jPanel2);

        txtBuscador.setText("Buscar");
        txtBuscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscadorMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/www.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)
                                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(panelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        JInicio.setText("Incio");
        jMenuBar1.add(JInicio);

        JUsuarios.setBackground(new java.awt.Color(51, 51, 255));
        JUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/people_114360.png"))); // NOI18N
        JUsuarios.setText("Usuarios");
        JUsuarios.setOpaque(true);
        jMenuBar1.add(JUsuarios);

        JLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/libro-de-registro.png"))); // NOI18N
        JLibros.setText("Libros");
        JLibros.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JLibrosMenuSelected(evt);
            }
        });
        jMenuBar1.add(JLibros);

        JPrestamo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pedir-prestado.png"))); // NOI18N
        JPrestamo.setText("Prestamos");
        JPrestamo.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                JPrestamoMenuSelected(evt);
            }
        });
        jMenuBar1.add(JPrestamo);

        JDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/devoluciones (1).png"))); // NOI18N
        JDevoluciones.setText("Devoluciones");
        jMenuBar1.add(JDevoluciones);

        JMultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/multa.png"))); // NOI18N
        JMultas.setText("Multas");
        jMenuBar1.add(JMultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreUsuarioMouseClicked
        // TODO add your handling code here:
        txtNombreUsuario.setText("");
    }//GEN-LAST:event_txtNombreUsuarioMouseClicked

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        // TODO add your handling code here:
        txtNombre.setText("");
    }//GEN-LAST:event_txtNombreMouseClicked

    private void txtNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyReleased
        // TODO add your handling code here:
         validaciones.getValidacionLetras(txtNombre, lblValidacion);
    }//GEN-LAST:event_txtNombreKeyReleased

    private void txtApellidoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoPMouseClicked
        // TODO add your handling code here:
        txtApellidoP.setText("");
    }//GEN-LAST:event_txtApellidoPMouseClicked

    private void txtApellidoPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoPKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtApellidoP, lblValidacion);
    }//GEN-LAST:event_txtApellidoPKeyReleased

    private void txtApellidoMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApellidoMMouseClicked
        // TODO add your handling code here:
         txtApellidoM.setText("");
    }//GEN-LAST:event_txtApellidoMMouseClicked

    private void txtApellidoMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoMKeyReleased
        // TODO add your handling code here:
        validaciones.getValidacionLetras(txtApellidoM, lblValidacion);
    }//GEN-LAST:event_txtApellidoMKeyReleased

    private void txtTelefonoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTelefonoMouseClicked
        // TODO add your handling code here:
         txtTelefono.setText("");
    }//GEN-LAST:event_txtTelefonoMouseClicked

    private void txtTelefonoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyReleased
        // TODO add your handling code here:
        validaciones.validacionTelefono(txtTelefono, txtTelefono, lblValidacion);
    }//GEN-LAST:event_txtTelefonoKeyReleased

    private void txtCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCorreoMouseClicked
        // TODO add your handling code here:
         txtCorreo.setText("");
    }//GEN-LAST:event_txtCorreoMouseClicked

    private void txtDomicilioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDomicilioMouseClicked
        // TODO add your handling code here:
        txtDomicilio.setText("");
    }//GEN-LAST:event_txtDomicilioMouseClicked

    private void btnInsertarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseEntered
        // TODO add your handling code here:
        btnInsertar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnInsertarMouseEntered

    private void btnInsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseExited
        // TODO add your handling code here:
        btnInsertar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnInsertarMouseExited

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnEditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseEntered
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnEditarMouseEntered

    private void btnEditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseExited
        // TODO add your handling code here:
        btnEditar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnEditarMouseExited

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseEntered
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(245, 0, 87));
    }//GEN-LAST:event_btnEliminarMouseEntered

    private void btnEliminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseExited
        // TODO add your handling code here:
        btnEliminar.setBackground(new Color(255, 64, 129));
    }//GEN-LAST:event_btnEliminarMouseExited

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
         try {
             // TODO add your handling code here:
             txtId.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 0));
             txtNombreUsuario.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 1));
             txtNombre.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 2));
             txtApellidoP.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 3));
             txtApellidoM.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 4));
             fechaNacimiento.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String) tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 5)));
             visualPassword.setPassword(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 6));
             txtTelefono.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 7));
             txtCorreo.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 8));
             txtDomicilio.setText(""+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 9));
             comboxTipoUsuario.setSelectedItem(tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(), 10));
             
         } catch (ParseException ex) {
             Logger.getLogger(Usuarios2.class.getName()).log(Level.SEVERE, null, ex);
         }
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void txtBuscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscadorMouseClicked
        // TODO add your handling code here:
        txtBuscador.setText("");
    }//GEN-LAST:event_txtBuscadorMouseClicked

    private void JLibrosMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JLibrosMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Libros vista=new Libros();
        controladorLibro controlador=new controladorLibro(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JLibrosMenuSelected

    private void JPrestamoMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_JPrestamoMenuSelected
        // TODO add your handling code here:
        this.dispose();
        Prestamos vista=new Prestamos();
        controladorPrestamo controlador=new controladorPrestamo(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
    }//GEN-LAST:event_JPrestamoMenuSelected

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Usuarios2 vista=new Usuarios2();
        ControladorUsuario controlador =new ControladorUsuario(vista);
        vista.setVisible(true);
        vista.setLocationRelativeTo(vista);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImagenLogin;
    private javax.swing.JMenu JDevoluciones;
    private javax.swing.JMenu JInicio;
    private javax.swing.JMenu JLibros;
    private javax.swing.JMenu JMultas;
    private javax.swing.JMenu JPrestamo;
    private javax.swing.JMenu JUsuarios;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnInsertar;
    public javax.swing.JComboBox<String> comboxTipoUsuario;
    public com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JLabel lblValidacion;
    public javax.swing.JPanel panelDatos;
    public javax.swing.JTable tablaUsuarios;
    public javax.swing.JTextField txtApellidoM;
    public javax.swing.JTextField txtApellidoP;
    public javax.swing.JTextField txtBuscador;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDomicilio;
    public javax.swing.JTextField txtId;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtNombreUsuario;
    public javax.swing.JTextField txtTelefono;
    public novisualbd.VisualPassword visualPassword;
    // End of variables declaration//GEN-END:variables
}
